import { CareerSuggestion, Question } from "@/types/general";

export const INITIAL_QUESTIONS: Question[] = [
  {
    id: "userName",
    question: "What's your name?",
    type: "text",
    required: true,
    validation: {
      minLength: 2,
      maxLength: 50,
    },
    group: "personal",
    helper: "This helps us personalize your results"
  },
  {
    id: "email",
    question: "What's your email? (Optional - for saving your results)",
    type: "text",
    required: false,
    validation: {
      pattern: /^[^\s@]+@[^\s@]+\.[^\s@]+$/,
    },
    group: "personal",
     helper: "We'll use this to save your results and send career insights"
  },
  {
    id: "age",
    question: "What's your age range?",
    type: "radio",
    options: ["Under 18", "18-24", "25-34", "35-44", "45-54", "55+"],
    required: true,
    group: "personal",
  },
  {
    id: "gender",
    question: "What's your gender?",
    type: "radio",
    options: ["Male", "Female", "Non-binary", "Prefer not to say", "Other"],
    required: false,
    group: "personal",
  },
  {
    id: "location",
    question: "Which region are you from?",
    type: "radio",
    options: [
      "North America",
      "South America",
      "Europe",
      "Asia",
      "Africa",
      "Oceania",
      "Middle East",
    ],
    required: true,
    group: "personal",
  },
];

export const CAREER_QUESTIONS: Question[] = [
  {
    id: "education",
    question: "What's your highest level of education?",
    type: "radio",
    options: [
      "High School",
      "Some College",
      "Associate's Degree",
      "Bachelor's Degree",
      "Master's Degree",
      "Doctorate (PhD)",
      "Professional Degree (MD, JD, etc.)",
      "Technical Certification",
      "Bootcamp/Specialized Training",
      "Self-Taught with Portfolio",
      "Other",
    ],
    required: true,
    group: "education",
  },
  {
    id: "fieldOfStudy",
    question: "What's your field of study or interest? (Select up to 2)",
    type: "multiSelect",
    options: [
      "Arts and Design",
      "Business and Management",
      "Computer Science and IT",
      "Data Science and Analytics",
      "Engineering and Robotics",
      "Environmental Science",
      "Healthcare and Medicine",
      "Life Sciences and Biotechnology",
      "Physical Sciences",
      "Mathematics",
      "Social Sciences",
      "Psychology and Behavioral Science",
      "Law and Policy",
      "Education and Training",
      "Media and Communications",
      "Agriculture and Food Science",
      "Space and Aviation",
      "Sustainability and Energy",
      "Other",
    ],
    validation: {
      maxSelections: 2,
    },
    required: true,
    group: "education",
     helper: "Choose the fields that most closely match your education or interests"
  },
  {
    id: "techComfort",
    question: "How comfortable are you with technology and digital tools?",
    type: "radio",
    options: [
      "Very Comfortable - I learn new tech quickly and enjoy it",
      "Comfortable - I can adapt to new tech when needed",
      "Moderate - I use basic tech but prefer minimal complexity",
      "Basic - I stick to simple tools and applications",
      "Limited - I prefer minimal technology use",
    ],
    required: true,
    group: "skills",
    helper: "This helps us match you with careers that align with your tech comfort level"
  },
  {
    id: "workStyle",
    question: "What's your preferred work style? (Select up to 2)",
    type: "multiSelect",
    options: [
      "Independent Problem Solver",
      "Collaborative Team Member",
      "Strategic Leader",
      "Creative Innovator",
      "Analytical Expert",
      "Support and Enable Others",
      "Project Manager",
      "Research and Development",
      "Customer/Client Focused",
      "Technical Specialist",
    ],
    validation: {
      maxSelections: 2,
    },
    required: true,
    group: "preferences",
  },
  {
    id: "workEnvironment",
    question: "What's your ideal work environment? (Select up to 2)",
    type: "multiSelect",
    options: [
      "Traditional Office",
      "Remote Work",
      "Hybrid/Flexible",
      "Laboratory/Research Facility",
      "Outdoor/Field Work",
      "Creative Studio",
      "High-Tech Facility",
      "Healthcare Setting",
      "Educational Institution",
      "Industrial/Manufacturing",
      "Travel/Multiple Locations",
      "Startup Environment",
    ],
    validation: {
      maxSelections: 2,
    },
    required: true,
    group: "preferences",
  },
  {
    id: "employment",
    question: "What type of employment interests you most? (Select up to 2)",
    type: "multiSelect",
    options: [
      "Corporate Employee",
      "Startup Employee",
      "Entrepreneur/Founder",
      "Freelancer/Contractor",
      "Government/Public Sector",
      "Non-profit/NGO",
      "Academic/Research",
      "Consulting",
      "Small Business Owner",
      "Innovation Lab",
    ],
    validation: {
      maxSelections: 2,
    },
    required: true,
    group: "preferences",
  },
  {
    id: "keyStrengths",
    question: "Select your top 4 strengths:",
    type: "multiSelect",
    options: [
      "Analytical Thinking",
      "Creative Problem Solving",
      "Strategic Planning",
      "Technical Expertise",
      "Research and Analysis",
      "Leadership and Management",
      "Communication and Presentation",
      "Project Management",
      "Innovation and Ideation",
      "Teaching and Mentoring",
      "Emotional Intelligence",
      "Adaptability",
      "Detail Orientation",
      "Critical Thinking",
      "Cross-cultural Awareness",
      "Systems Thinking",
    ],
    validation: {
      maxSelections: 4,
    },
    required: true,
    group: "skills",
  },
  {
    id: "interests",
    question: "What topics interest you the most? (Select up to 4)",
    type: "multiSelect",
    options: [
      "Artificial Intelligence/ML",
      "Sustainability/Climate",
      "Healthcare Innovation",
      "Space Exploration",
      "Biotechnology",
      "Digital Technology",
      "Creative Arts",
      "Business Strategy",
      "Social Impact",
      "Scientific Research",
      "Education/Learning",
      "Environmental Protection",
      "Human Behavior",
      "Data and Analytics",
      "Engineering Systems",
      "Policy and Governance",
      "Virtual/Augmented Reality",
      "Robotics and Automation",
      "Financial Technology",
      "Ocean/Marine Science",
    ],
    validation: {
      maxSelections: 4,
    },
    required: true,
    group: "interests",
  },
  {
    id: "values",
    question: "What do you value most in a career? (Select up to 4)",
    type: "multiSelect",
    options: [
      "Work-Life Balance",
      "High Income Potential",
      "Job Security",
      "Making a Difference",
      "Continuous Learning",
      "Career Growth",
      "Innovation and Creativity",
      "Social Impact",
      "Professional Recognition",
      "Independence and Autonomy",
      "Environmental Impact",
      "Scientific Discovery",
      "Technological Advancement",
      "Global Influence",
      "Ethical Practice",
      "Cultural Exchange",
      "Leadership Opportunities",
      "Research and Development",
      "Entrepreneurial Freedom",
      "Collaborative Culture",
    ],
    validation: {
      maxSelections: 4,
    },
    required: true,
    group: "values",
  },
  {
    id: "challengePreference",
    question: "What type of challenges do you enjoy? (Select up to 3)",
    type: "multiSelect",
    options: [
      "Complex Problem Solving",
      "Creative Design Challenges",
      "Technical Puzzles",
      "Research Questions",
      "People and Leadership Challenges",
      "Strategic Planning",
      "Innovation and Invention",
      "Social/Cultural Challenges",
      "Environmental Challenges",
      "Business/Market Challenges",
      "Scientific Discovery",
      "Technological Development",
    ],
    validation: {
      maxSelections: 3,
    },
    required: true,
    group: "preferences",
  },
  {
    id: "impact",
    question: "What kind of impact would you like to make in your career?",
    type: "textarea",
    placeholder:
      "Consider areas like technology advancement, social change, environmental protection, healthcare improvement, scientific discovery, or business innovation...",
    required: true,
    validation: {
      minLength: 50,
      maxLength: 500,
    },
    group: "aspirations",
  },
  {
    id: "futureInterest",
    question: "Which emerging fields interest you? (Select up to 3)",
    type: "multiSelect",
    options: [
      "Artificial Intelligence Ethics",
      "Space Technology",
      "Climate Tech",
      "Quantum Computing",
      "Biotechnology",
      "Neurotechnology",
      "Robotics and Automation",
      "Virtual/Augmented Reality",
      "Blockchain/Web3",
      "Sustainable Energy",
      "Smart Cities",
      "Digital Health",
      "Ocean Technology",
      "Synthetic Biology",
    ],
    validation: {
      maxSelections: 3,
    },
    required: true,
    group: "interests",
  },
  {
    id: "fiveYearGoal",
    question: "Where do you see yourself in 5 years?",
    type: "textarea",
    placeholder:
      "Consider your role, impact, skills, and the type of problems you want to solve...",
    required: true,
    validation: {
      minLength: 50,
      maxLength: 500,
    },
    group: "aspirations",
  },
];

export const CAREER_SUGGESTIONS: Record<string, CareerSuggestion> = {
  technology: {
    software_engineer: {
      title: "Software Engineer",
      confidence: 0.9,
      description:
        "Design, develop, and maintain software applications and systems using programming languages, frameworks, and best practices. Collaborate with teams to create efficient, scalable solutions.",
      skills: [
        "Programming",
        "Problem Solving",
        "System Design",
        "Debugging",
        "Version Control",
        "Algorithms",
        "Data Structures",
        "Testing",
        "API Development",
        "Database Design",
      ],
      education: [
        "Bachelor's in Computer Science",
        "Bachelor's in Software Engineering",
        "Coding Bootcamp",
        "Self-taught with portfolio",
        "Software Engineering Certifications",
      ],
      matchingFactors: {
        interests: [
          "Technology",
          "Innovation",
          "Problem Solving",
          "Engineering",
          "Mathematics",
        ],
        strengths: [
          "Analytical Thinking",
          "Problem Solving",
          "Technical Skills",
          "Attention to Detail",
        ],
        values: [
          "High Income",
          "Learning Opportunities",
          "Innovation",
          "Work-Life Balance",
          "Remote Work",
        ],
      },
      salary: {
        entry: 75000,
        mid: 120000,
        senior: 200000,
      },
      growthOutlook: "Very High",
      workEnvironment: ["Remote", "Office", "Hybrid"],
      sectors: [
        "Tech",
        "Finance",
        "Healthcare",
        "Entertainment",
        "E-commerce",
        "Education",
      ],
    },
    data_scientist: {
      title: "Data Scientist",
      confidence: 0.85,
      description:
        "Apply statistical analysis, machine learning, and programming to extract meaningful insights from complex data sets. Transform data into actionable business strategies.",
      skills: [
        "Machine Learning",
        "Statistics",
        "Python/R Programming",
        "SQL",
        "Data Visualization",
        "Big Data Technologies",
        "Deep Learning",
        "Data Mining",
        "Predictive Modeling",
        "A/B Testing",
      ],
      education: [
        "Master's in Data Science",
        "Master's in Statistics",
        "PhD in Related Field",
        "Bachelor's with Strong Analytics Background",
      ],
      matchingFactors: {
        interests: [
          "Data Analysis",
          "Machine Learning",
          "Research",
          "Technology",
          "Mathematics",
        ],
        strengths: [
          "Analytical Thinking",
          "Statistical Analysis",
          "Problem Solving",
          "Research",
        ],
        values: [
          "Innovation",
          "High Income",
          "Learning Opportunities",
          "Impact",
        ],
      },
      salary: {
        entry: 85000,
        mid: 130000,
        senior: 180000,
      },
      growthOutlook: "Very High",
      workEnvironment: ["Hybrid", "Office", "Remote"],
      sectors: ["Tech", "Finance", "Healthcare", "Research", "Consulting"],
    },
    cloud_architect: {
      title: "Cloud Architect",
      confidence: 0.85,
      description:
        "Design and oversee cloud computing infrastructure, ensuring scalability, security, and efficiency of cloud-based systems.",
      skills: [
        "Cloud Platforms (AWS/Azure/GCP)",
        "Infrastructure as Code",
        "Network Security",
        "System Architecture",
        "DevOps",
        "Containerization",
        "Microservices",
        "Cost Optimization",
        "Disaster Recovery",
        "Performance Tuning",
      ],
      education: [
        "Bachelor's in Computer Science",
        "Master's in Cloud Computing",
        "Cloud Certifications",
        "IT Infrastructure Experience",
      ],
      matchingFactors: {
        interests: [
          "Cloud Computing",
          "Infrastructure",
          "Security",
          "Architecture",
          "Technology",
        ],
        strengths: [
          "System Design",
          "Problem Solving",
          "Technical Leadership",
          "Strategic Thinking",
        ],
        values: [
          "Innovation",
          "Technical Excellence",
          "Security",
          "Scalability",
        ],
      },
      salary: {
        entry: 100000,
        mid: 150000,
        senior: 200000,
      },
      growthOutlook: "Very High",
      workEnvironment: ["Remote", "Office", "Hybrid"],
      sectors: ["Tech", "Finance", "Enterprise", "Consulting"],
    },
    cybersecurity_analyst: {
      title: "Cybersecurity Analyst",
      confidence: 0.88,
      description:
        "Protect organizations from cyber threats by monitoring, detecting, investigating, and responding to security incidents.",
      skills: [
        "Security Tools",
        "Threat Detection",
        "Incident Response",
        "Network Security",
        "Penetration Testing",
        "Security Frameworks",
        "Risk Assessment",
        "Forensics",
        "Compliance",
        "Security Architecture",
      ],
      education: [
        "Bachelor's in Cybersecurity",
        "Bachelor's in Computer Science",
        "Security Certifications",
        "Information Security Degree",
      ],
      matchingFactors: {
        interests: [
          "Cybersecurity",
          "Technology",
          "Investigation",
          "Protection",
          "Risk Management",
        ],
        strengths: [
          "Analytical Thinking",
          "Problem Solving",
          "Attention to Detail",
          "Technical Skills",
        ],
        values: ["Security", "Protection", "Innovation", "Integrity"],
      },
      salary: {
        entry: 75000,
        mid: 110000,
        senior: 160000,
      },
      growthOutlook: "Very High",
      workEnvironment: ["Office", "Remote", "Hybrid"],
      sectors: ["Tech", "Finance", "Government", "Healthcare"],
    },
  },
  healthcare: {
    nurse_practitioner: {
      title: "Nurse Practitioner",
      confidence: 0.88,
      description:
        "Provide advanced nursing care, diagnose and treat various health conditions, prescribe medications, and work closely with healthcare teams to ensure quality patient care.",
      skills: [
        "Patient Care",
        "Clinical Assessment",
        "Medical Knowledge",
        "Prescription Management",
        "Health Education",
        "Communication",
        "Decision Making",
        "Electronic Health Records",
        "Care Coordination",
        "Clinical Procedures",
      ],
      education: [
        "Master's in Nursing",
        "Bachelor's in Nursing",
        "Nurse Practitioner License",
        "Clinical Experience",
      ],
      matchingFactors: {
        interests: [
          "Healthcare",
          "Patient Care",
          "Medicine",
          "Science",
          "Education",
        ],
        strengths: [
          "Communication",
          "Empathy",
          "Clinical Skills",
          "Decision Making",
        ],
        values: [
          "Making a Difference",
          "Healthcare Access",
          "Patient Care",
          "Work-Life Balance",
        ],
      },
      salary: {
        entry: 90000,
        mid: 120000,
        senior: 150000,
      },
      growthOutlook: "Very High",
      workEnvironment: ["Hospital", "Clinic", "Private Practice"],
      sectors: ["Healthcare", "Education", "Research"],
    },
    healthcare_administrator: {
      title: "Healthcare Administrator",
      confidence: 0.82,
      description:
        "Manage healthcare facilities, improve patient care systems, and ensure regulatory compliance while optimizing operational efficiency.",
      skills: [
        "Healthcare Management",
        "Leadership",
        "Regulatory Compliance",
        "Budget Management",
        "Staff Coordination",
        "Quality Assurance",
        "Policy Development",
        "Strategic Planning",
        "Communication",
        "Risk Management",
      ],
      education: [
        "Master's in Healthcare Administration",
        "Master's in Business Administration",
        "Bachelor's in Healthcare Management",
      ],
      matchingFactors: {
        interests: [
          "Healthcare",
          "Management",
          "Leadership",
          "Business",
          "Policy",
        ],
        strengths: [
          "Leadership",
          "Organization",
          "Problem Solving",
          "Communication",
        ],
        values: [
          "Healthcare Improvement",
          "Leadership",
          "Impact",
          "Career Growth",
        ],
      },
      salary: {
        entry: 65000,
        mid: 95000,
        senior: 150000,
      },
      growthOutlook: "High",
      workEnvironment: ["Hospital", "Clinic", "Office"],
      sectors: ["Healthcare", "Government", "Non-profit"],
    },
    medical_researcher: {
      title: "Medical Researcher",
      confidence: 0.85,
      description:
        "Conduct research to advance medical knowledge, develop new treatments, and improve healthcare outcomes.",
      skills: [
        "Research Methods",
        "Data Analysis",
        "Clinical Trials",
        "Laboratory Techniques",
        "Scientific Writing",
        "Statistical Analysis",
        "Protocol Development",
        "Grant Writing",
        "Literature Review",
        "Experimental Design",
      ],
      education: [
        "PhD in Life Sciences",
        "MD/PhD",
        "Master's in Medical Research",
        "Research Experience",
      ],
      matchingFactors: {
        interests: [
          "Medical Research",
          "Science",
          "Healthcare",
          "Innovation",
          "Discovery",
        ],
        strengths: [
          "Research",
          "Analysis",
          "Scientific Thinking",
          "Attention to Detail",
        ],
        values: [
          "Scientific Discovery",
          "Medical Advancement",
          "Impact",
          "Innovation",
        ],
      },
      salary: {
        entry: 70000,
        mid: 100000,
        senior: 150000,
      },
      growthOutlook: "High",
      workEnvironment: ["Laboratory", "Research Facility", "Academic"],
      sectors: ["Healthcare", "Research", "Academia", "Pharmaceutical"],
    },
    physical_therapist: {
      title: "Physical Therapist",
      confidence: 0.87,
      description:
        "Help patients improve movement, manage pain, and recover from injuries through exercise and rehabilitation techniques.",
      skills: [
        "Patient Assessment",
        "Treatment Planning",
        "Exercise Prescription",
        "Manual Therapy",
        "Rehabilitation",
        "Patient Education",
        "Documentation",
        "Anatomy Knowledge",
        "Pain Management",
        "Movement Analysis",
      ],
      education: [
        "Doctor of Physical Therapy",
        "Physical Therapy License",
        "Clinical Experience",
        "Specialization Certifications",
      ],
      matchingFactors: {
        interests: [
          "Healthcare",
          "Rehabilitation",
          "Fitness",
          "Patient Care",
          "Movement Science",
        ],
        strengths: [
          "Patient Care",
          "Communication",
          "Physical Skills",
          "Problem Solving",
        ],
        values: ["Patient Recovery", "Healthcare", "Impact", "Wellness"],
      },
      salary: {
        entry: 70000,
        mid: 85000,
        senior: 100000,
      },
      growthOutlook: "High",
      workEnvironment: ["Clinic", "Hospital", "Private Practice"],
      sectors: ["Healthcare", "Sports", "Rehabilitation"],
    },
  },
  business: {
    management_consultant: {
      title: "Management Consultant",
      confidence: 0.85,
      description:
        "Help organizations improve performance through analysis of existing problems and development of plans for improvement.",
      skills: [
        "Business Analysis",
        "Strategy Development",
        "Project Management",
        "Problem Solving",
        "Data Analysis",
        "Presentation",
        "Change Management",
        "Process Improvement",
        "Client Management",
        "Industry Research",
      ],
      education: [
        "MBA",
        "Bachelor's in Business",
        "Master's in Management",
        "Consulting Certifications",
      ],
      matchingFactors: {
        interests: [
          "Business",
          "Strategy",
          "Analysis",
          "Problem Solving",
          "Leadership",
        ],
        strengths: [
          "Analysis",
          "Communication",
          "Leadership",
          "Problem Solving",
        ],
        values: ["Impact", "Excellence", "Innovation", "Results"],
      },
      salary: {
        entry: 85000,
        mid: 150000,
        senior: 250000,
      },
      growthOutlook: "High",
      workEnvironment: ["Client Site", "Office", "Travel"],
      sectors: ["Consulting", "Corporate", "Strategy"],
    },
    product_manager: {
      title: "Product Manager",
      confidence: 0.88,
      description:
        "Lead the development and strategy of products, working with various teams to ensure successful product launches and iterations.",
      skills: [
        "Product Strategy",
        "User Research",
        "Roadmap Planning",
        "Stakeholder Management",
        "Market Analysis",
        "Agile Methodologies",
        "Data Analysis",
        "Feature Prioritization",
        "Cross-functional Leadership",
        "Product Analytics",
      ],
      education: [
        "Bachelor's in Business",
        "Bachelor's in Technology",
        "MBA",
        "Product Management Certifications",
      ],
      matchingFactors: {
        interests: [
          "Product Development",
          "Technology",
          "Business",
          "Innovation",
          "User Experience",
        ],
        strengths: ["Leadership", "Strategy", "Communication", "Analysis"],
        values: ["Innovation", "User Focus", "Impact", "Quality"],
      },
      salary: {
        entry: 80000,
        mid: 120000,
        senior: 180000,
      },
      growthOutlook: "Very High",
      workEnvironment: ["Office", "Remote", "Hybrid"],
      sectors: ["Tech", "Product", "Software", "Consumer Goods"],
    },
  },
  finance: {
    financial_analyst: {
      title: "Financial Analyst",
      confidence: 0.85,
      description:
        "Analyze financial data, market trends, and investment opportunities to guide business decisions and investment strategies.",
      skills: [
        "Financial Analysis",
        "Excel",
        "Financial Modeling",
        "Market Research",
        "Risk Assessment",
        "Forecasting",
        "Data Analysis",
        "Investment Analysis",
        "Business Intelligence",
        "Statistical Analysis",
      ],
      education: [
        "Bachelor's in Finance",
        "Bachelor's in Economics",
        "MBA",
        "CFA Certification",
      ],
      matchingFactors: {
        interests: ["Finance", "Economics", "Markets", "Analysis", "Business"],
        strengths: [
          "Analytical Thinking",
          "Numerical Skills",
          "Research",
          "Attention to Detail",
        ],
        values: ["High Income", "Professional Growth", "Analysis", "Impact"],
      },
      salary: {
        entry: 65000,
        mid: 95000,
        senior: 140000,
      },
      growthOutlook: "High",
      workEnvironment: ["Office", "Hybrid"],
      sectors: ["Finance", "Banking", "Corporate", "Investment"],
    },
    investment_banker: {
      title: "Investment Banker",
      confidence: 0.8,
      description:
        "Facilitate major financial transactions, mergers and acquisitions, and help companies raise capital through various financial instruments.",
      skills: [
        "Financial Analysis",
        "Deal Structuring",
        "Valuation",
        "Negotiation",
        "Presentation",
        "Client Relations",
        "Market Analysis",
        "Due Diligence",
        "Financial Modeling",
        "Strategic Thinking",
      ],
      education: [
        "MBA",
        "Bachelor's in Finance",
        "Bachelor's in Economics",
        "Master's in Finance",
      ],
      matchingFactors: {
        interests: ["Finance", "Business", "Markets", "Deals", "Strategy"],
        strengths: [
          "Analytical Thinking",
          "Negotiation",
          "Communication",
          "Leadership",
        ],
        values: [
          "High Income",
          "Professional Success",
          "Achievement",
          "Impact",
        ],
      },
      salary: {
        entry: 95000,
        mid: 150000,
        senior: 300000,
      },
      growthOutlook: "Moderate",
      workEnvironment: ["Office"],
      sectors: ["Investment Banking", "Finance", "Corporate"],
    },
  },
  creative: {
    ux_designer: {
      title: "UX Designer",
      confidence: 0.88,
      description:
        "Design user-friendly digital experiences and interfaces, focusing on user research, wireframing, and prototyping to create intuitive products.",
      skills: [
        "User Research",
        "Wireframing",
        "Prototyping",
        "UI Design",
        "User Testing",
        "Information Architecture",
        "Visual Design",
        "Design Thinking",
        "Interaction Design",
        "Design Tools",
      ],
      education: [
        "Bachelor's in Design",
        "Bachelor's in HCI",
        "UX/UI Certifications",
        "Design Portfolio",
      ],
      matchingFactors: {
        interests: [
          "Design",
          "Technology",
          "Psychology",
          "User Behavior",
          "Creativity",
        ],
        strengths: [
          "Creativity",
          "Empathy",
          "Problem Solving",
          "Communication",
        ],
        values: [
          "User Experience",
          "Innovation",
          "Design Impact",
          "Creativity",
        ],
      },
      salary: {
        entry: 70000,
        mid: 100000,
        senior: 150000,
      },
      growthOutlook: "High",
      workEnvironment: ["Remote", "Office", "Hybrid"],
      sectors: ["Tech", "Design", "Consulting", "Agency"],
    },
    content_creator: {
      title: "Content Creator",
      confidence: 0.75,
      description:
        "Create engaging digital content across various platforms, including social media, blogs, videos, and podcasts to build audience engagement.",
      skills: [
        "Content Strategy",
        "Writing",
        "Video Production",
        "Social Media",
        "Storytelling",
        "Photography",
        "Editing",
        "Analytics",
        "Brand Development",
        "Community Management",
      ],
      education: [
        "Bachelor's in Communications",
        "Bachelor's in Marketing",
        "Digital Media Certifications",
        "Portfolio of Work",
      ],
      matchingFactors: {
        interests: [
          "Digital Media",
          "Creativity",
          "Communication",
          "Social Media",
          "Entertainment",
        ],
        strengths: ["Creativity", "Communication", "Visual Skills", "Strategy"],
        values: ["Creative Freedom", "Independence", "Innovation", "Impact"],
      },
      salary: {
        entry: 45000,
        mid: 75000,
        senior: 120000,
      },
      growthOutlook: "High",
      workEnvironment: ["Remote", "Hybrid", "Studio"],
      sectors: ["Media", "Entertainment", "Marketing", "Tech"],
    },
    game_developer: {
      title: "Game Developer",
      confidence: 0.85,
      description:
        "Create and program video games, combining technical skills with creativity to develop engaging gaming experiences.",
      skills: [
        "Game Programming",
        "Game Engines",
        "3D Graphics",
        "Game Design",
        "Animation",
        "Physics Programming",
        "AI Programming",
        "Sound Integration",
        "Version Control",
        "Testing",
      ],
      education: [
        "Bachelor's in Game Development",
        "Computer Science Degree",
        "Game Design Degree",
        "Portfolio of Games",
      ],
      matchingFactors: {
        interests: [
          "Gaming",
          "Programming",
          "Design",
          "Animation",
          "Entertainment",
        ],
        strengths: [
          "Creativity",
          "Technical Skills",
          "Problem Solving",
          "Attention to Detail",
        ],
        values: [
          "Creative Expression",
          "Innovation",
          "Entertainment",
          "Technical Excellence",
        ],
      },
      salary: {
        entry: 65000,
        mid: 90000,
        senior: 140000,
      },
      growthOutlook: "High",
      workEnvironment: ["Studio", "Remote", "Office"],
      sectors: ["Gaming", "Entertainment", "Tech", "Media"],
    },
    art_director: {
      title: "Art Director",
      confidence: 0.82,
      description:
        "Lead the visual style and creative direction of projects across various media, managing creative teams and ensuring brand consistency.",
      skills: [
        "Visual Design",
        "Creative Direction",
        "Team Management",
        "Brand Development",
        "Project Management",
        "Design Software",
        "Typography",
        "Color Theory",
        "Marketing",
        "Presentation",
      ],
      education: [
        "Bachelor's in Fine Arts",
        "Bachelor's in Design",
        "Art School Degree",
        "Extensive Portfolio",
      ],
      matchingFactors: {
        interests: [
          "Art",
          "Design",
          "Leadership",
          "Creativity",
          "Visual Media",
        ],
        strengths: [
          "Creative Vision",
          "Leadership",
          "Visual Skills",
          "Communication",
        ],
        values: [
          "Creativity",
          "Excellence",
          "Innovation",
          "Artistic Expression",
        ],
      },
      salary: {
        entry: 70000,
        mid: 100000,
        senior: 150000,
      },
      growthOutlook: "Moderate",
      workEnvironment: ["Studio", "Agency", "Office"],
      sectors: ["Advertising", "Media", "Entertainment", "Publishing"],
    },
  },
  education: {
    instructional_designer: {
      title: "Instructional Designer",
      confidence: 0.82,
      description:
        "Develop educational content and learning experiences for various platforms, combining pedagogy with technology to create effective learning solutions.",
      skills: [
        "Curriculum Development",
        "E-learning",
        "Learning Management Systems",
        "Educational Technology",
        "Content Creation",
        "Assessment Design",
        "Project Management",
        "Multimedia Design",
        "Teaching Methods",
        "Learning Theory",
      ],
      education: [
        "Master's in Instructional Design",
        "Master's in Education",
        "Bachelor's in Education",
        "Teaching Experience",
      ],
      matchingFactors: {
        interests: [
          "Education",
          "Technology",
          "Design",
          "Learning",
          "Innovation",
        ],
        strengths: ["Creativity", "Communication", "Organization", "Teaching"],
        values: ["Education", "Impact", "Innovation", "Learning"],
      },
      salary: {
        entry: 60000,
        mid: 85000,
        senior: 120000,
      },
      growthOutlook: "High",
      workEnvironment: ["Remote", "Office", "Hybrid"],
      sectors: ["Education", "Corporate", "Tech", "Consulting"],
    },
  },
  environmental: {
    sustainability_consultant: {
      title: "Sustainability Consultant",
      confidence: 0.8,
      description:
        "Help organizations develop and implement sustainable practices, reduce environmental impact, and achieve environmental compliance goals.",
      skills: [
        "Environmental Analysis",
        "Sustainability Planning",
        "Carbon Footprint Analysis",
        "Environmental Regulations",
        "Project Management",
        "Stakeholder Management",
        "Research",
        "Reporting",
        "Data Analysis",
        "Green Building Standards",
      ],
      education: [
        "Master's in Environmental Science",
        "Master's in Sustainability",
        "Bachelor's in Environmental Studies",
        "Professional Certifications",
      ],
      matchingFactors: {
        interests: [
          "Environment",
          "Sustainability",
          "Business",
          "Science",
          "Policy",
        ],
        strengths: ["Analysis", "Communication", "Problem Solving", "Research"],
        values: [
          "Environmental Impact",
          "Sustainability",
          "Social Responsibility",
          "Innovation",
        ],
      },
      salary: {
        entry: 55000,
        mid: 85000,
        senior: 130000,
      },
      growthOutlook: "Very High",
      workEnvironment: ["Office", "Remote", "Field"],
      sectors: ["Consulting", "Corporate", "Government", "Non-profit"],
    },
  },
  science: {
    data_engineer: {
      title: "Data Engineer",
      confidence: 0.87,
      description:
        "Design and build systems for collecting, storing, and analyzing large datasets, ensuring data quality and accessibility.",
      skills: [
        "Data Pipelines",
        "ETL Processes",
        "Database Design",
        "Big Data Technologies",
        "SQL",
        "Python",
        "Data Modeling",
        "Cloud Platforms",
        "Data Warehousing",
        "Data Security",
      ],
      education: [
        "Bachelor's in Computer Science",
        "Bachelor's in Data Engineering",
        "Master's in Data Science",
        "Technical Certifications",
      ],
      matchingFactors: {
        interests: [
          "Data",
          "Engineering",
          "Technology",
          "Analytics",
          "Infrastructure",
        ],
        strengths: [
          "Technical Skills",
          "Problem Solving",
          "Attention to Detail",
          "System Design",
        ],
        values: [
          "Data Quality",
          "Efficiency",
          "Innovation",
          "Technical Excellence",
        ],
      },
      salary: {
        entry: 80000,
        mid: 120000,
        senior: 170000,
      },
      growthOutlook: "Very High",
      workEnvironment: ["Office", "Remote", "Hybrid"],
      sectors: ["Tech", "Finance", "Healthcare", "Research"],
    },
    research_scientist: {
      title: "Research Scientist",
      confidence: 0.85,
      description:
        "Conduct advanced research in specialized fields, developing new theories, methodologies, and applications.",
      skills: [
        "Research Methods",
        "Data Analysis",
        "Scientific Writing",
        "Experimental Design",
        "Statistical Analysis",
        "Grant Writing",
        "Lab Techniques",
        "Project Management",
        "Literature Review",
        "Technical Documentation",
      ],
      education: [
        "PhD in Related Field",
        "Master's Degree",
        "Research Experience",
        "Publications",
      ],
      matchingFactors: {
        interests: [
          "Research",
          "Science",
          "Discovery",
          "Innovation",
          "Analysis",
        ],
        strengths: [
          "Research",
          "Analysis",
          "Scientific Thinking",
          "Problem Solving",
        ],
        values: ["Scientific Discovery", "Innovation", "Knowledge", "Impact"],
      },
      salary: {
        entry: 70000,
        mid: 100000,
        senior: 150000,
      },
      growthOutlook: "High",
      workEnvironment: ["Laboratory", "Research Facility", "Academic"],
      sectors: ["Research", "Academia", "Industry", "Government"],
    },
  },
  legal: {
    corporate_lawyer: {
      title: "Corporate Lawyer",
      confidence: 0.88,
      description:
        "Advise businesses on legal rights, obligations, and transactions, handling corporate governance, mergers, acquisitions, and compliance matters.",
      skills: [
        "Corporate Law",
        "Contract Negotiation",
        "Legal Research",
        "Due Diligence",
        "Regulatory Compliance",
        "Business Acumen",
        "Legal Writing",
        "Risk Assessment",
        "Client Management",
        "Case Management",
      ],
      education: [
        "Juris Doctor (JD)",
        "Bar Admission",
        "Bachelor's Degree",
        "Corporate Law Specialization",
      ],
      matchingFactors: {
        interests: [
          "Law",
          "Business",
          "Corporate Affairs",
          "Regulations",
          "Negotiations",
        ],
        strengths: [
          "Analysis",
          "Communication",
          "Attention to Detail",
          "Negotiation",
        ],
        values: [
          "Professional Excellence",
          "Ethics",
          "Impact",
          "Client Service",
        ],
      },
      salary: {
        entry: 100000,
        mid: 160000,
        senior: 250000,
      },
      growthOutlook: "Moderate",
      workEnvironment: ["Office", "Remote", "Court"],
      sectors: ["Legal", "Corporate", "Finance"],
    },
    public_defender: {
      title: "Public Defender",
      confidence: 0.85,
      description:
        "Represent and defend individuals who cannot afford private legal representation in criminal cases.",
      skills: [
        "Criminal Law",
        "Trial Advocacy",
        "Legal Research",
        "Case Management",
        "Client Advocacy",
        "Negotiation",
        "Court Procedures",
        "Evidence Analysis",
        "Public Speaking",
        "Investigation",
      ],
      education: [
        "Juris Doctor (JD)",
        "Bar Admission",
        "Criminal Law Experience",
        "Trial Experience",
      ],
      matchingFactors: {
        interests: [
          "Criminal Justice",
          "Public Service",
          "Advocacy",
          "Law",
          "Social Justice",
        ],
        strengths: ["Advocacy", "Communication", "Empathy", "Analysis"],
        values: ["Justice", "Public Service", "Equal Rights", "Social Impact"],
      },
      salary: {
        entry: 55000,
        mid: 75000,
        senior: 100000,
      },
      growthOutlook: "Stable",
      workEnvironment: ["Court", "Office", "Correctional Facilities"],
      sectors: ["Legal", "Public Service", "Criminal Justice"],
    },
  },
  engineering: {
    mechanical_engineer: {
      title: "Mechanical Engineer",
      confidence: 0.9,
      description:
        "Design, develop, and test mechanical devices, including tools, engines, and machines.",
      skills: [
        "CAD/CAM",
        "Product Design",
        "Thermodynamics",
        "Manufacturing Processes",
        "Materials Science",
        "Project Management",
        "3D Modeling",
        "Structural Analysis",
        "Quality Control",
        "Technical Documentation",
      ],
      education: [
        "Bachelor's in Mechanical Engineering",
        "Master's in Mechanical Engineering",
        "Professional Engineering License",
        "Engineering Certifications",
      ],
      matchingFactors: {
        interests: [
          "Engineering",
          "Design",
          "Manufacturing",
          "Innovation",
          "Technology",
        ],
        strengths: [
          "Technical Skills",
          "Problem Solving",
          "Analysis",
          "Design Thinking",
        ],
        values: ["Innovation", "Technical Excellence", "Safety", "Quality"],
      },
      salary: {
        entry: 70000,
        mid: 95000,
        senior: 130000,
      },
      growthOutlook: "High",
      workEnvironment: ["Office", "Manufacturing", "Lab", "Field"],
      sectors: ["Manufacturing", "Automotive", "Aerospace", "Energy"],
    },
    civil_engineer: {
      title: "Civil Engineer",
      confidence: 0.88,
      description:
        "Design and oversee construction projects including roads, buildings, airports, tunnels, dams, and water supply systems.",
      skills: [
        "Structural Design",
        "Project Management",
        "AutoCAD",
        "Construction Methods",
        "Site Planning",
        "Environmental Impact",
        "Cost Estimation",
        "Quality Control",
        "Safety Standards",
        "Surveying",
      ],
      education: [
        "Bachelor's in Civil Engineering",
        "Master's in Civil Engineering",
        "Professional Engineering License",
        "Construction Management Certifications",
      ],
      matchingFactors: {
        interests: [
          "Construction",
          "Infrastructure",
          "Design",
          "Urban Development",
          "Environment",
        ],
        strengths: [
          "Project Management",
          "Technical Skills",
          "Problem Solving",
          "Analysis",
        ],
        values: [
          "Infrastructure Development",
          "Safety",
          "Sustainability",
          "Quality",
        ],
      },
      salary: {
        entry: 65000,
        mid: 90000,
        senior: 125000,
      },
      growthOutlook: "High",
      workEnvironment: ["Office", "Construction Site", "Field"],
      sectors: ["Construction", "Government", "Consulting", "Infrastructure"],
    },
  },
  transportation: {
    logistics_manager: {
      title: "Logistics Manager",
      confidence: 0.85,
      description:
        "Oversee supply chain operations, coordinate transportation, manage inventory, and optimize delivery systems.",
      skills: [
        "Supply Chain Management",
        "Inventory Control",
        "Transportation Planning",
        "Warehouse Management",
        "Route Optimization",
        "Cost Analysis",
        "Vendor Management",
        "Risk Management",
        "ERP Systems",
        "Team Leadership",
      ],
      education: [
        "Bachelor's in Logistics",
        "Bachelor's in Supply Chain Management",
        "Supply Chain Certifications",
        "Business Administration Degree",
      ],
      matchingFactors: {
        interests: [
          "Logistics",
          "Operations",
          "Management",
          "Transportation",
          "Efficiency",
        ],
        strengths: [
          "Organization",
          "Problem Solving",
          "Leadership",
          "Analysis",
        ],
        values: ["Efficiency", "Reliability", "Quality", "Service Excellence"],
      },
      salary: {
        entry: 60000,
        mid: 85000,
        senior: 120000,
      },
      growthOutlook: "High",
      workEnvironment: ["Office", "Warehouse", "Field"],
      sectors: ["Logistics", "Retail", "Manufacturing", "E-commerce"],
    },
    transportation_planner: {
      title: "Transportation Planner",
      confidence: 0.82,
      description:
        "Plan and develop transportation systems, considering factors like urban growth, environmental impact, and public needs.",
      skills: [
        "Transportation Planning",
        "GIS Software",
        "Data Analysis",
        "Urban Planning",
        "Public Policy",
        "Project Management",
        "Environmental Impact",
        "Traffic Analysis",
        "Stakeholder Management",
        "Budget Planning",
      ],
      education: [
        "Master's in Transportation Planning",
        "Master's in Urban Planning",
        "Bachelor's in Civil Engineering",
        "Planning Certifications",
      ],
      matchingFactors: {
        interests: [
          "Urban Planning",
          "Transportation",
          "Public Policy",
          "Environment",
          "Community Development",
        ],
        strengths: ["Analysis", "Planning", "Communication", "Problem Solving"],
        values: [
          "Sustainability",
          "Public Service",
          "Community Impact",
          "Innovation",
        ],
      },
      salary: {
        entry: 55000,
        mid: 75000,
        senior: 100000,
      },
      growthOutlook: "Moderate",
      workEnvironment: ["Office", "Field", "Government"],
      sectors: ["Government", "Urban Planning", "Consulting"],
    },
  },
  political: {
    policy_analyst: {
      title: "Policy Analyst",
      confidence: 0.85,
      description:
        "Research, analyze, and evaluate public policies and their impacts, providing recommendations for improvement.",
      skills: [
        "Policy Analysis",
        "Research Methods",
        "Data Analysis",
        "Report Writing",
        "Stakeholder Management",
        "Legislative Process",
        "Public Speaking",
        "Impact Assessment",
        "Statistical Analysis",
        "Political Systems",
      ],
      education: [
        "Master's in Public Policy",
        "Master's in Political Science",
        "Bachelor's in Related Field",
        "Policy Research Experience",
      ],
      matchingFactors: {
        interests: [
          "Politics",
          "Policy",
          "Research",
          "Government",
          "Social Impact",
        ],
        strengths: ["Analysis", "Research", "Writing", "Critical Thinking"],
        values: ["Public Service", "Impact", "Ethics", "Social Change"],
      },
      salary: {
        entry: 55000,
        mid: 80000,
        senior: 120000,
      },
      growthOutlook: "Moderate",
      workEnvironment: ["Office", "Government", "Think Tank"],
      sectors: ["Government", "Non-profit", "Consulting", "Research"],
    },
    campaign_manager: {
      title: "Campaign Manager",
      confidence: 0.8,
      description:
        "Direct and coordinate political campaigns, managing strategy, messaging, fundraising, and voter outreach.",
      skills: [
        "Campaign Strategy",
        "Team Management",
        "Fundraising",
        "Media Relations",
        "Voter Outreach",
        "Event Planning",
        "Budget Management",
        "Social Media",
        "Crisis Management",
        "Political Communication",
      ],
      education: [
        "Bachelor's in Political Science",
        "Bachelor's in Communications",
        "Campaign Experience",
        "Political Management Degree",
      ],
      matchingFactors: {
        interests: [
          "Politics",
          "Campaigns",
          "Leadership",
          "Communication",
          "Strategy",
        ],
        strengths: ["Leadership", "Strategy", "Communication", "Organization"],
        values: [
          "Political Impact",
          "Leadership",
          "Public Service",
          "Democracy",
        ],
      },
      salary: {
        entry: 45000,
        mid: 75000,
        senior: 120000,
      },
      growthOutlook: "Cyclical",
      workEnvironment: ["Campaign Office", "Field", "Travel"],
      sectors: ["Politics", "Advocacy", "Consulting"],
    },
  },
  aviation: {
    commercial_pilot: {
      title: "Commercial Pilot",
      confidence: 0.9,
      description:
        "Operate aircraft for airlines, conducting pre-flight checks, navigating flights, and ensuring passenger safety.",
      skills: [
        "Flight Operations",
        "Navigation",
        "Safety Procedures",
        "Weather Analysis",
        "Communication",
        "Decision Making",
        "Aircraft Systems",
        "Emergency Procedures",
        "Crew Resource Management",
        "Regulations Compliance",
      ],
      education: [
        "Commercial Pilot License",
        "Airline Transport Pilot License",
        "Flight Training",
        "Aviation Degree",
      ],
      matchingFactors: {
        interests: [
          "Aviation",
          "Travel",
          "Technology",
          "Safety",
          "Transportation",
        ],
        strengths: [
          "Technical Skills",
          "Decision Making",
          "Communication",
          "Attention to Detail",
        ],
        values: [
          "Safety",
          "Responsibility",
          "Professional Excellence",
          "Service",
        ],
      },
      salary: {
        entry: 45000,
        mid: 100000,
        senior: 200000,
      },
      growthOutlook: "Moderate",
      workEnvironment: ["Aircraft", "Airport", "Travel"],
      sectors: ["Airlines", "Charter", "Corporate Aviation"],
    },
    aerospace_engineer: {
      title: "Aerospace Engineer",
      confidence: 0.88,
      description:
        "Design, develop, and test aircraft, spacecraft, satellites, and missiles.",
      skills: [
        "Aerodynamics",
        "CAD Design",
        "Propulsion Systems",
        "Materials Science",
        "Systems Engineering",
        "Project Management",
        "Structural Analysis",
        "Testing Procedures",
        "Quality Control",
        "Technical Documentation",
      ],
      education: [
        "Bachelor's in Aerospace Engineering",
        "Master's in Aerospace Engineering",
        "Engineering License",
        "Specialized Certifications",
      ],
      matchingFactors: {
        interests: [
          "Aviation",
          "Space",
          "Engineering",
          "Innovation",
          "Technology",
        ],
        strengths: [
          "Technical Skills",
          "Analysis",
          "Problem Solving",
          "Design",
        ],
        values: ["Innovation", "Safety", "Technical Excellence", "Advancement"],
      },
      salary: {
        entry: 75000,
        mid: 110000,
        senior: 160000,
      },
      growthOutlook: "High",
      workEnvironment: ["Office", "Lab", "Manufacturing"],
      sectors: ["Aerospace", "Defense", "Research", "Government"],
    },
  },
  tourism: {
    travel_consultant: {
      title: "Travel Consultant",
      confidence: 0.85,
      description:
        "Plan and arrange travel experiences for clients, providing expert advice on destinations, accommodations, and activities while ensuring smooth travel logistics.",
      skills: [
        "Travel Planning",
        "Customer Service",
        "Destination Knowledge",
        "Booking Systems",
        "Cultural Awareness",
        "Problem Solving",
        "Sales",
        "Negotiation",
        "Documentation",
        "Crisis Management",
      ],
      education: [
        "Bachelor's in Tourism Management",
        "Travel and Tourism Diploma",
        "Hospitality Management Degree",
        "Industry Certifications",
      ],
      matchingFactors: {
        interests: [
          "Travel",
          "Culture",
          "Customer Service",
          "Planning",
          "Geography",
        ],
        strengths: [
          "Organization",
          "Communication",
          "Cultural Sensitivity",
          "Problem Solving",
        ],
        values: [
          "Customer Satisfaction",
          "Cultural Exchange",
          "Service Excellence",
          "Adventure",
        ],
      },
      salary: {
        entry: 35000,
        mid: 50000,
        senior: 75000,
      },
      growthOutlook: "Moderate",
      workEnvironment: ["Office", "Remote", "Travel Agency"],
      sectors: ["Tourism", "Hospitality", "Travel"],
    },
    tour_guide: {
      title: "Tour Guide",
      confidence: 0.82,
      description:
        "Lead and educate groups of visitors through cultural, historical, or natural sites, providing engaging commentary and ensuring safety and enjoyment.",
      skills: [
        "Public Speaking",
        "Historical Knowledge",
        "Group Management",
        "Storytelling",
        "First Aid",
        "Language Skills",
        "Cultural Knowledge",
        "Safety Procedures",
        "Route Planning",
        "Customer Service",
      ],
      education: [
        "Tourism Certificate",
        "Bachelor's in History",
        "Tour Guide License",
        "Language Certifications",
      ],
      matchingFactors: {
        interests: ["History", "Culture", "Education", "Travel", "People"],
        strengths: [
          "Communication",
          "Leadership",
          "Knowledge Sharing",
          "Organization",
        ],
        values: [
          "Cultural Exchange",
          "Education",
          "Adventure",
          "People Connection",
        ],
      },
      salary: {
        entry: 30000,
        mid: 45000,
        senior: 65000,
      },
      growthOutlook: "Moderate",
      workEnvironment: ["Outdoors", "Tourist Sites", "Travel"],
      sectors: ["Tourism", "Education", "Culture"],
    },
  },
  fashion: {
    fashion_designer: {
      title: "Fashion Designer",
      confidence: 0.88,
      description:
        "Create and develop clothing and accessory designs, from concept to final product, considering trends, materials, and market demands.",
      skills: [
        "Design",
        "Pattern Making",
        "Sketching",
        "Fashion CAD",
        "Textile Knowledge",
        "Color Theory",
        "Trend Analysis",
        "Technical Drawing",
        "Collection Development",
        "Materials Sourcing",
      ],
      education: [
        "Bachelor's in Fashion Design",
        "Fashion Design Diploma",
        "Design School Certificate",
        "Portfolio Development",
      ],
      matchingFactors: {
        interests: ["Fashion", "Design", "Art", "Creativity", "Trends"],
        strengths: [
          "Creativity",
          "Visual Skills",
          "Technical Skills",
          "Innovation",
        ],
        values: [
          "Artistic Expression",
          "Innovation",
          "Quality",
          "Sustainability",
        ],
      },
      salary: {
        entry: 45000,
        mid: 75000,
        senior: 120000,
      },
      growthOutlook: "Moderate",
      workEnvironment: ["Studio", "Workshop", "Office"],
      sectors: ["Fashion", "Design", "Retail"],
    },
    fashion_buyer: {
      title: "Fashion Buyer",
      confidence: 0.85,
      description:
        "Select and purchase clothing and accessories for retail stores, analyzing trends, sales data, and customer preferences to make strategic buying decisions.",
      skills: [
        "Market Analysis",
        "Trend Forecasting",
        "Negotiation",
        "Budget Management",
        "Product Selection",
        "Vendor Relations",
        "Sales Analysis",
        "Fashion Knowledge",
        "Inventory Planning",
        "Strategic Planning",
      ],
      education: [
        "Bachelor's in Fashion Merchandising",
        "Business Degree",
        "Retail Management Degree",
        "Fashion Business Diploma",
      ],
      matchingFactors: {
        interests: ["Fashion", "Business", "Trends", "Retail", "Analysis"],
        strengths: [
          "Analysis",
          "Decision Making",
          "Negotiation",
          "Fashion Sense",
        ],
        values: [
          "Market Success",
          "Customer Satisfaction",
          "Innovation",
          "Quality",
        ],
      },
      salary: {
        entry: 50000,
        mid: 80000,
        senior: 130000,
      },
      growthOutlook: "Moderate",
      workEnvironment: ["Office", "Market", "Travel"],
      sectors: ["Fashion", "Retail", "Business"],
    },
  },
  hospitality: {
    hotel_manager: {
      title: "Hotel Manager",
      confidence: 0.87,
      description:
        "Oversee all aspects of hotel operations, ensuring excellent guest experiences while managing staff, budgets, and facility maintenance.",
      skills: [
        "Operations Management",
        "Customer Service",
        "Staff Leadership",
        "Budget Management",
        "Crisis Management",
        "Revenue Management",
        "Event Planning",
        "Quality Control",
        "Marketing",
        "Property Management",
      ],
      education: [
        "Bachelor's in Hospitality Management",
        "Hotel Management Degree",
        "Business Administration Degree",
        "Hospitality Certifications",
      ],
      matchingFactors: {
        interests: [
          "Hospitality",
          "Management",
          "Customer Service",
          "Leadership",
          "Operations",
        ],
        strengths: [
          "Leadership",
          "Organization",
          "Problem Solving",
          "Communication",
        ],
        values: [
          "Service Excellence",
          "Leadership",
          "Quality",
          "Customer Satisfaction",
        ],
      },
      salary: {
        entry: 55000,
        mid: 85000,
        senior: 130000,
      },
      growthOutlook: "Moderate",
      workEnvironment: ["Hotel", "Resort", "Office"],
      sectors: ["Hospitality", "Management", "Tourism"],
    },
    executive_chef: {
      title: "Executive Chef",
      confidence: 0.86,
      description:
        "Lead kitchen operations, create menus, manage culinary staff, and ensure high-quality food preparation and presentation.",
      skills: [
        "Culinary Expertise",
        "Menu Planning",
        "Kitchen Management",
        "Food Safety",
        "Team Leadership",
        "Cost Control",
        "Inventory Management",
        "Recipe Development",
        "Quality Control",
        "Food Presentation",
      ],
      education: [
        "Culinary Arts Degree",
        "Chef Training Program",
        "Food Service Management Degree",
        "Culinary Certifications",
      ],
      matchingFactors: {
        interests: [
          "Cooking",
          "Food",
          "Management",
          "Creativity",
          "Leadership",
        ],
        strengths: [
          "Culinary Skills",
          "Leadership",
          "Creativity",
          "Organization",
        ],
        values: ["Quality", "Creativity", "Leadership", "Excellence"],
      },
      salary: {
        entry: 50000,
        mid: 80000,
        senior: 120000,
      },
      growthOutlook: "Moderate",
      workEnvironment: ["Kitchen", "Restaurant", "Hotel"],
      sectors: ["Hospitality", "Food Service", "Culinary"],
    },
  },
  news_media: {
    journalist: {
      title: "Journalist",
      confidence: 0.84,
      description:
        "Research, investigate, and report news stories across various media platforms, ensuring accuracy and engaging storytelling.",
      skills: [
        "Writing",
        "Research",
        "Interviewing",
        "Fact Checking",
        "News Judgment",
        "Digital Media",
        "Storytelling",
        "Investigation",
        "Editing",
        "Media Law Knowledge",
      ],
      education: [
        "Bachelor's in Journalism",
        "Communications Degree",
        "Media Studies Degree",
        "Journalism Certifications",
      ],
      matchingFactors: {
        interests: [
          "News",
          "Writing",
          "Current Events",
          "Investigation",
          "Communication",
        ],
        strengths: ["Writing", "Research", "Communication", "Analysis"],
        values: ["Truth", "Integrity", "Public Service", "Impact"],
      },
      salary: {
        entry: 35000,
        mid: 60000,
        senior: 90000,
      },
      growthOutlook: "Moderate",
      workEnvironment: ["Newsroom", "Field", "Remote"],
      sectors: ["Media", "News", "Publishing"],
    },
    news_producer: {
      title: "News Producer",
      confidence: 0.83,
      description:
        "Coordinate and oversee news broadcasts, managing content selection, timing, and production elements.",
      skills: [
        "News Judgment",
        "Production Management",
        "Content Planning",
        "Team Coordination",
        "Deadline Management",
        "Script Writing",
        "Video Production",
        "Live Broadcasting",
        "Story Development",
        "Crisis Management",
      ],
      education: [
        "Bachelor's in Broadcasting",
        "Journalism Degree",
        "Media Production Degree",
        "Communications Degree",
      ],
      matchingFactors: {
        interests: [
          "News",
          "Production",
          "Media",
          "Leadership",
          "Current Events",
        ],
        strengths: [
          "Leadership",
          "Organization",
          "Decision Making",
          "Communication",
        ],
        values: ["News Quality", "Timeliness", "Public Service", "Accuracy"],
      },
      salary: {
        entry: 40000,
        mid: 70000,
        senior: 100000,
      },
      growthOutlook: "Moderate",
      workEnvironment: ["TV Studio", "Newsroom", "Control Room"],
      sectors: ["Media", "Broadcasting", "News"],
    },
  },
  renewable_energy: {
    solar_energy_engineer: {
      title: "Solar Energy Engineer",
      confidence: 0.88,
      description:
        "Design, develop, and implement solar energy systems and technologies for residential, commercial, and industrial applications.",
      skills: [
        "Solar System Design",
        "Energy Analysis",
        "Project Management",
        "CAD Software",
        "Electrical Systems",
        "Performance Modeling",
        "Technical Documentation",
        "Site Assessment",
        "Regulatory Compliance",
        "Energy Storage Systems",
      ],
      education: [
        "Bachelor's in Renewable Energy Engineering",
        "Bachelor's in Electrical Engineering",
        "Solar Energy Certifications",
        "Professional Engineering License",
      ],
      matchingFactors: {
        interests: [
          "Renewable Energy",
          "Engineering",
          "Sustainability",
          "Technology",
          "Environment",
        ],
        strengths: [
          "Technical Skills",
          "Problem Solving",
          "Design",
          "Analysis",
        ],
        values: [
          "Sustainability",
          "Innovation",
          "Environmental Impact",
          "Technical Excellence",
        ],
      },
      salary: {
        entry: 65000,
        mid: 95000,
        senior: 140000,
      },
      growthOutlook: "Very High",
      workEnvironment: ["Office", "Field", "Laboratory"],
      sectors: ["Energy", "Engineering", "Environment"],
    },
  },
  biotech: {
    genetic_counselor: {
      title: "Genetic Counselor",
      confidence: 0.86,
      description:
        "Assess genetic risk for inherited conditions and guide patients and families through genetic testing decisions and results.",
      skills: [
        "Genetic Analysis",
        "Patient Counseling",
        "Medical Knowledge",
        "Risk Assessment",
        "Communication",
        "Psychology",
        "Research Skills",
        "Documentation",
        "Ethics",
        "Family History Analysis",
      ],
      education: [
        "Master's in Genetic Counseling",
        "Genetic Counseling Certification",
        "Bachelor's in Biology/Genetics",
        "Clinical Training",
      ],
      matchingFactors: {
        interests: [
          "Genetics",
          "Healthcare",
          "Counseling",
          "Science",
          "Patient Care",
        ],
        strengths: [
          "Communication",
          "Analysis",
          "Empathy",
          "Scientific Knowledge",
        ],
        values: ["Patient Care", "Ethics", "Education", "Support"],
      },
      salary: {
        entry: 70000,
        mid: 95000,
        senior: 120000,
      },
      growthOutlook: "High",
      workEnvironment: ["Hospital", "Clinic", "Research Center"],
      sectors: ["Healthcare", "Genetics", "Counseling"],
    },
  },
  esports: {
    esports_coach: {
      title: "Esports Coach",
      confidence: 0.82,
      description:
        "Train and develop professional gaming teams, analyze strategies, and improve team performance in competitive gaming environments.",
      skills: [
        "Game Strategy",
        "Team Leadership",
        "Performance Analysis",
        "Communication",
        "Mental Training",
        "Competition Planning",
        "Game Knowledge",
        "Team Building",
        "Video Analysis",
        "Conflict Resolution",
      ],
      education: [
        "Esports Management Degree",
        "Sports Psychology Degree",
        "Gaming Experience",
        "Coaching Certifications",
      ],
      matchingFactors: {
        interests: [
          "Gaming",
          "Competition",
          "Coaching",
          "Strategy",
          "Technology",
        ],
        strengths: ["Leadership", "Strategy", "Communication", "Analysis"],
        values: ["Competition", "Excellence", "Team Success", "Innovation"],
      },
      salary: {
        entry: 40000,
        mid: 75000,
        senior: 120000,
      },
      growthOutlook: "High",
      workEnvironment: ["Gaming Facility", "Remote", "Competition Venues"],
      sectors: ["Esports", "Gaming", "Entertainment"],
    },
  },
  space_industry: {
    space_mission_planner: {
      title: "Space Mission Planner",
      confidence: 0.85,
      description:
        "Design and coordinate space missions, including trajectory planning, resource allocation, and mission objectives for both crewed and uncrewed missions.",
      skills: [
        "Mission Planning",
        "Orbital Mechanics",
        "Risk Management",
        "Systems Engineering",
        "Project Management",
        "Space Systems",
        "Data Analysis",
        "Technical Writing",
        "Simulation",
        "Collaboration",
      ],
      education: [
        "Master's in Aerospace Engineering",
        "Space Systems Degree",
        "Mission Planning Certification",
        "Project Management Professional",
      ],
      matchingFactors: {
        interests: [
          "Space",
          "Engineering",
          "Planning",
          "Science",
          "Technology",
        ],
        strengths: [
          "Strategic Planning",
          "Technical Skills",
          "Problem Solving",
          "Leadership",
        ],
        values: ["Exploration", "Innovation", "Safety", "Achievement"],
      },
      salary: {
        entry: 80000,
        mid: 120000,
        senior: 180000,
      },
      growthOutlook: "High",
      workEnvironment: ["Mission Control", "Office", "Research Facility"],
      sectors: ["Space", "Aerospace", "Research"],
    },
  },
  blockchain: {
    blockchain_developer: {
      title: "Blockchain Developer",
      confidence: 0.87,
      description:
        "Design and implement blockchain protocols, smart contracts, and decentralized applications.",
      skills: [
        "Blockchain Protocols",
        "Smart Contracts",
        "Cryptography",
        "DApp Development",
        "Solidity",
        "Web3",
        "Security",
        "Distributed Systems",
        "Testing",
        "API Development",
      ],
      education: [
        "Computer Science Degree",
        "Blockchain Certifications",
        "Cryptography Training",
        "Software Engineering Background",
      ],
      matchingFactors: {
        interests: [
          "Blockchain",
          "Cryptocurrency",
          "Programming",
          "Innovation",
          "Security",
        ],
        strengths: [
          "Technical Skills",
          "Problem Solving",
          "Innovation",
          "Security Mindset",
        ],
        values: ["Innovation", "Decentralization", "Security", "Technology"],
      },
      salary: {
        entry: 90000,
        mid: 140000,
        senior: 200000,
      },
      growthOutlook: "Very High",
      workEnvironment: ["Remote", "Office", "Tech Company"],
      sectors: ["Blockchain", "Technology", "Finance"],
    },
  },
  virtual_reality: {
    vr_experience_designer: {
      title: "VR Experience Designer",
      confidence: 0.84,
      description:
        "Create immersive virtual reality experiences, focusing on user interaction, environment design, and spatial storytelling.",
      skills: [
        "3D Modeling",
        "User Experience Design",
        "Unity/Unreal Engine",
        "Spatial Design",
        "Animation",
        "Interaction Design",
        "Prototyping",
        "User Testing",
        "Sound Design",
        "Visual Effects",
      ],
      education: [
        "Bachelor's in Interactive Design",
        "VR/AR Development Degree",
        "Game Design Degree",
        "3D Design Certification",
      ],
      matchingFactors: {
        interests: [
          "Virtual Reality",
          "Design",
          "Technology",
          "Gaming",
          "Innovation",
        ],
        strengths: [
          "Creativity",
          "Technical Skills",
          "Design Thinking",
          "Innovation",
        ],
        values: ["Innovation", "User Experience", "Creativity", "Technology"],
      },
      salary: {
        entry: 65000,
        mid: 95000,
        senior: 140000,
      },
      growthOutlook: "Very High",
      workEnvironment: ["Studio", "Tech Company", "Gaming Company"],
      sectors: ["Virtual Reality", "Gaming", "Technology"],
    },
  },
  sustainability: {
    sustainability_consultant: {
      title: "Sustainability Consultant",
      confidence: 0.86,
      description:
        "Help organizations develop and implement sustainable practices, reduce environmental impact, and achieve ESG goals.",
      skills: [
        "Environmental Analysis",
        "ESG Reporting",
        "Carbon Footprint Assessment",
        "Sustainability Strategy",
        "Stakeholder Management",
        "Environmental Regulations",
        "Data Analysis",
        "Project Management",
        "Green Building Standards",
        "Life Cycle Assessment",
      ],
      education: [
        "Master's in Environmental Science",
        "Sustainability Management Degree",
        "Environmental Engineering Degree",
        "Sustainability Certifications",
      ],
      matchingFactors: {
        interests: [
          "Environment",
          "Sustainability",
          "Consulting",
          "Business",
          "Climate",
        ],
        strengths: ["Analysis", "Communication", "Problem Solving", "Strategy"],
        values: [
          "Sustainability",
          "Environmental Impact",
          "Social Responsibility",
          "Innovation",
        ],
      },
      salary: {
        entry: 60000,
        mid: 90000,
        senior: 140000,
      },
      growthOutlook: "Very High",
      workEnvironment: ["Office", "Client Sites", "Remote"],
      sectors: ["Sustainability", "Consulting", "Environment"],
    },
  },
  quantum_computing: {
    quantum_engineer: {
      title: "Quantum Engineer",
      confidence: 0.83,
      description:
        "Design and develop quantum computing systems, algorithms, and applications for solving complex computational problems.",
      skills: [
        "Quantum Mechanics",
        "Quantum Programming",
        "Algorithm Development",
        "Mathematics",
        "Physics",
        "Circuit Design",
        "Error Correction",
        "System Architecture",
        "Problem Solving",
        "Research",
      ],
      education: [
        "PhD in Physics/Engineering",
        "Master's in Quantum Computing",
        "Quantum Engineering Degree",
        "Advanced Mathematics Background",
      ],
      matchingFactors: {
        interests: [
          "Quantum Computing",
          "Physics",
          "Technology",
          "Mathematics",
          "Research",
        ],
        strengths: [
          "Technical Skills",
          "Problem Solving",
          "Research",
          "Innovation",
        ],
        values: [
          "Innovation",
          "Scientific Discovery",
          "Technology",
          "Research",
        ],
      },
      salary: {
        entry: 90000,
        mid: 140000,
        senior: 200000,
      },
      growthOutlook: "Very High",
      workEnvironment: ["Laboratory", "Research Center", "Tech Company"],
      sectors: ["Quantum Computing", "Technology", "Research"],
    },
  },
  ai_ethics: {
    ai_ethics_officer: {
      title: "AI Ethics Officer",
      confidence: 0.85,
      description:
        "Ensure ethical development and deployment of AI systems, addressing bias, fairness, transparency, and societal impact.",
      skills: [
        "AI Systems Understanding",
        "Ethical Framework Development",
        "Bias Detection",
        "Risk Assessment",
        "Policy Development",
        "Stakeholder Management",
        "Compliance",
        "Research",
        "Communication",
        "Impact Analysis",
      ],
      education: [
        "Master's in AI Ethics",
        "Ethics and Technology Degree",
        "Philosophy Degree",
        "AI/ML Background",
      ],
      matchingFactors: {
        interests: ["AI", "Ethics", "Technology", "Policy", "Social Impact"],
        strengths: [
          "Critical Thinking",
          "Analysis",
          "Communication",
          "Leadership",
        ],
        values: ["Ethics", "Responsibility", "Fairness", "Social Impact"],
      },
      salary: {
        entry: 85000,
        mid: 130000,
        senior: 180000,
      },
      growthOutlook: "Very High",
      workEnvironment: ["Tech Company", "Research Institution", "Consulting"],
      sectors: ["AI", "Ethics", "Technology"],
    },
    algorithmic_auditor: {
      title: "Algorithmic Auditor",
      confidence: 0.83,
      description:
        "Evaluate AI algorithms for bias, fairness, and ethical compliance, ensuring responsible AI deployment.",
      skills: [
        "Algorithm Analysis",
        "Statistical Testing",
        "Bias Detection",
        "Data Science",
        "Machine Learning",
        "Documentation",
        "Risk Assessment",
        "Compliance",
        "Programming",
        "Ethics",
      ],
      education: [
        "Master's in Computer Science",
        "AI/ML Degree",
        "Ethics Training",
        "Auditing Certifications",
      ],
      matchingFactors: {
        interests: ["AI", "Ethics", "Analysis", "Technology", "Fairness"],
        strengths: [
          "Technical Skills",
          "Analysis",
          "Attention to Detail",
          "Ethics",
        ],
        values: ["Fairness", "Accountability", "Transparency", "Ethics"],
      },
      salary: {
        entry: 75000,
        mid: 120000,
        senior: 160000,
      },
      growthOutlook: "High",
      workEnvironment: ["Tech Company", "Consulting", "Research"],
      sectors: ["AI", "Ethics", "Technology"],
    },
  },
  smart_city: {
    smart_city_planner: {
      title: "Smart City Planner",
      confidence: 0.86,
      description:
        "Design and implement intelligent urban systems integrating technology for improved city operations and citizen services.",
      skills: [
        "Urban Planning",
        "IoT Systems",
        "Data Analytics",
        "Project Management",
        "Sustainability",
        "Infrastructure Design",
        "Smart Technology",
        "Stakeholder Management",
        "Systems Integration",
        "Policy Development",
      ],
      education: [
        "Master's in Urban Planning",
        "Smart Cities Degree",
        "Technology Management Degree",
        "Engineering Background",
      ],
      matchingFactors: {
        interests: [
          "Urban Development",
          "Technology",
          "Planning",
          "Sustainability",
          "Innovation",
        ],
        strengths: ["Planning", "Technical Skills", "Strategy", "Innovation"],
        values: [
          "Sustainability",
          "Innovation",
          "Community Impact",
          "Efficiency",
        ],
      },
      salary: {
        entry: 70000,
        mid: 110000,
        senior: 150000,
      },
      growthOutlook: "High",
      workEnvironment: ["Office", "Field", "Government"],
      sectors: ["Urban Planning", "Technology", "Government"],
    },
  },
  biotech_manufacturing: {
    bioprocess_engineer: {
      title: "Bioprocess Engineer",
      confidence: 0.88,
      description:
        "Design and optimize biological manufacturing processes for pharmaceuticals, vaccines, and other biological products.",
      skills: [
        "Bioprocess Design",
        "Process Optimization",
        "Quality Control",
        "GMP Compliance",
        "Scale-up Operations",
        "Automation",
        "Documentation",
        "Project Management",
        "Technical Problem Solving",
        "Risk Management",
      ],
      education: [
        "Master's in Bioengineering",
        "Chemical Engineering Degree",
        "GMP Certification",
        "Process Engineering Background",
      ],
      matchingFactors: {
        interests: [
          "Biotechnology",
          "Manufacturing",
          "Engineering",
          "Science",
          "Production",
        ],
        strengths: [
          "Technical Skills",
          "Problem Solving",
          "Analysis",
          "Attention to Detail",
        ],
        values: ["Quality", "Safety", "Innovation", "Efficiency"],
      },
      salary: {
        entry: 75000,
        mid: 115000,
        senior: 160000,
      },
      growthOutlook: "Very High",
      workEnvironment: ["Manufacturing Facility", "Laboratory", "Office"],
      sectors: ["Biotech", "Manufacturing", "Pharmaceuticals"],
    },
  },
  digital_psychology: {
    digital_behavior_analyst: {
      title: "Digital Behavior Analyst",
      confidence: 0.84,
      description:
        "Study and analyze human behavior in digital environments to improve user experience and digital well-being.",
      skills: [
        "Behavioral Analysis",
        "Data Analytics",
        "Psychology",
        "UX Research",
        "Digital Metrics",
        "Statistical Analysis",
        "Research Design",
        "User Testing",
        "Report Writing",
        "Digital Ethics",
      ],
      education: [
        "Master's in Psychology",
        "Digital Psychology Degree",
        "UX Research Certification",
        "Behavioral Science Background",
      ],
      matchingFactors: {
        interests: [
          "Psychology",
          "Technology",
          "Research",
          "Human Behavior",
          "Digital Media",
        ],
        strengths: ["Analysis", "Research", "Communication", "Problem Solving"],
        values: ["Understanding", "Well-being", "Ethics", "Innovation"],
      },
      salary: {
        entry: 65000,
        mid: 95000,
        senior: 135000,
      },
      growthOutlook: "High",
      workEnvironment: ["Research Lab", "Tech Company", "Consulting"],
      sectors: ["Psychology", "Technology", "Research"],
    },
  },
  space_agriculture: {
    space_agriculture_specialist: {
      title: "Space Agriculture Specialist",
      confidence: 0.82,
      description:
        "Develop and maintain food production systems for space missions and extraterrestrial settlements.",
      skills: [
        "Hydroponics",
        "Plant Science",
        "Life Support Systems",
        "Resource Management",
        "Environmental Control",
        "System Monitoring",
        "Research",
        "Data Analysis",
        "Problem Solving",
        "Experimental Design",
      ],
      education: [
        "Master's in Agriculture",
        "Space Science Degree",
        "Botany Degree",
        "Engineering Background",
      ],
      matchingFactors: {
        interests: [
          "Space",
          "Agriculture",
          "Science",
          "Research",
          "Innovation",
        ],
        strengths: [
          "Technical Skills",
          "Research",
          "Problem Solving",
          "Innovation",
        ],
        values: ["Sustainability", "Innovation", "Exploration", "Science"],
      },
      salary: {
        entry: 70000,
        mid: 100000,
        senior: 140000,
      },
      growthOutlook: "High",
      workEnvironment: ["Research Facility", "Laboratory", "Space Agency"],
      sectors: ["Space", "Agriculture", "Research"],
    },
  },
  robotic_healthcare: {
    medical_robotics_engineer: {
      title: "Medical Robotics Engineer",
      confidence: 0.87,
      description:
        "Design and develop robotic systems for medical procedures, rehabilitation, and patient care.",
      skills: [
        "Robotics Engineering",
        "Medical Device Design",
        "Control Systems",
        "Programming",
        "Medical Knowledge",
        "Safety Standards",
        "Testing",
        "Documentation",
        "Problem Solving",
        "Project Management",
      ],
      education: [
        "Master's in Robotics Engineering",
        "Biomedical Engineering Degree",
        "Medical Device Certifications",
        "Programming Background",
      ],
      matchingFactors: {
        interests: [
          "Robotics",
          "Healthcare",
          "Engineering",
          "Technology",
          "Innovation",
        ],
        strengths: [
          "Technical Skills",
          "Problem Solving",
          "Innovation",
          "Attention to Detail",
        ],
        values: ["Healthcare Innovation", "Safety", "Quality", "Impact"],
      },
      salary: {
        entry: 85000,
        mid: 130000,
        senior: 180000,
      },
      growthOutlook: "Very High",
      workEnvironment: [
        "Research Lab",
        "Medical Facility",
        "Engineering Office",
      ],
      sectors: ["Healthcare", "Robotics", "Engineering"],
    },
  },
  neurotechnology: {
    neural_interface_developer: {
      title: "Neural Interface Developer",
      confidence: 0.85,
      description:
        "Design and develop brain-computer interfaces and neural technology applications.",
      skills: [
        "Neural Engineering",
        "Signal Processing",
        "Programming",
        "Neuroscience",
        "Hardware Design",
        "Data Analysis",
        "Machine Learning",
        "Research",
        "Documentation",
        "Testing",
      ],
      education: [
        "PhD in Neural Engineering",
        "Master's in Neuroscience",
        "Computer Science Degree",
        "Biomedical Engineering",
      ],
      matchingFactors: {
        interests: [
          "Neuroscience",
          "Technology",
          "Research",
          "Innovation",
          "Healthcare",
        ],
        strengths: [
          "Technical Skills",
          "Research",
          "Innovation",
          "Problem Solving",
        ],
        values: ["Innovation", "Healthcare", "Research", "Impact"],
      },
      salary: {
        entry: 90000,
        mid: 140000,
        senior: 200000,
      },
      growthOutlook: "Very High",
      workEnvironment: ["Research Lab", "Tech Company", "Medical Facility"],
      sectors: ["Neurotechnology", "Healthcare", "Research"],
    },
  },
  ocean_technology: {
    marine_technology_specialist: {
      title: "Marine Technology Specialist",
      confidence: 0.84,
      description:
        "Develop and operate advanced technology for ocean exploration, research, and conservation.",
      skills: [
        "Marine Systems",
        "ROV Operation",
        "Data Collection",
        "Ocean Mapping",
        "Equipment Maintenance",
        "Research Methods",
        "Environmental Monitoring",
        "Technical Writing",
        "Project Management",
        "Safety Procedures",
      ],
      education: [
        "Master's in Marine Technology",
        "Oceanography Degree",
        "Marine Engineering",
        "Technical Certifications",
      ],
      matchingFactors: {
        interests: [
          "Ocean",
          "Technology",
          "Research",
          "Environment",
          "Exploration",
        ],
        strengths: [
          "Technical Skills",
          "Research",
          "Problem Solving",
          "Operation",
        ],
        values: [
          "Ocean Conservation",
          "Research",
          "Exploration",
          "Environment",
        ],
      },
      salary: {
        entry: 65000,
        mid: 95000,
        senior: 140000,
      },
      growthOutlook: "High",
      workEnvironment: ["Research Vessel", "Laboratory", "Field"],
      sectors: ["Marine", "Technology", "Research"],
    },
  },
};
