import { CareerSuggestion, Question } from "@/types/general";

export const INITIAL_QUESTIONS: Question[] = [
  {
    id: "userName",
    question: "What's your name?",
    type: "text",
    required: true,
    validation: {
      minLength: 2,
      maxLength: 50,
    },
    group: "personal",
  },
  {
    id: "email",
    question: "What's your email? (Optional - for saving your results)",
    type: "text",
    required: false,
    validation: {
      pattern: /^[^\s@]+@[^\s@]+\.[^\s@]+$/,
    },
    group: "personal",
  },
  {
    id: "age",
    question: "What's your age range?",
    type: "radio",
    options: ["Under 18", "18-24", "25-34", "35-44", "45-54", "55+"],
    required: true,
    group: "personal",
  },
  {
    id: "gender",
    question: "What's your gender?",
    type: "radio",
    options: ["Male", "Female", "Non-binary", "Prefer not to say", "Other"],
    required: false,
    group: "personal",
  },
  {
    id: "location",
    question: "Which region are you from?",
    type: "radio",
    options: [
      "North America",
      "South America",
      "Europe",
      "Asia",
      "Africa",
      "Oceania",
      "Middle East",
    ],
    required: true,
    group: "personal",
  },
];

export const CAREER_QUESTIONS: Question[] = [
  {
    id: "education",
    question: "What's your highest level of education?",
    type: "radio",
    options: [
      "High School",
      "Some College",
      "Associate's Degree",
      "Bachelor's Degree",
      "Master's Degree",
      "Doctorate",
      "Professional Degree",
      "Other",
    ],
    required: true,
    group: "education",
  },
  {
    id: "fieldOfStudy",
    question: "What's your field of study or interest?",
    type: "radio",
    options: [
      "Arts and Humanities",
      "Business and Management",
      "Computer Science and IT",
      "Engineering",
      "Healthcare and Medicine",
      "Natural Sciences",
      "Social Sciences",
      "Education",
      "Law",
      "Other",
    ],
    required: true,
    group: "education",
  },
  {
    id: "workStyle",
    question: "What's your preferred work style?",
    type: "radio",
    options: [
      "Independent Work",
      "Team Collaboration",
      "Mix of Both",
      "Leadership Role",
      "Support Role",
    ],
    required: true,
    group: "preferences",
  },
  {
    id: "workEnvironment",
    question: "What's your ideal work environment?",
    type: "radio",
    options: [
      "Office Setting",
      "Remote Work",
      "Hybrid",
      "Outdoor/Field Work",
      "Laboratory/Research Setting",
      "Creative Studio",
    ],
    required: true,
    group: "preferences",
  },
  {
    id: "employment",
    question: "What type of employment interests you most?",
    type: "radio",
    options: [
      "Full-time Employee",
      "Entrepreneur/Business Owner",
      "Freelancer/Contractor",
      "Government/Public Sector",
      "Non-profit/NGO",
      "Academic/Research",
    ],
    required: true,
    group: "preferences",
  },
  {
    id: "keyStrengths",
    question: "Select your top 3 strengths:",
    type: "multiSelect",
    options: [
      "Analytical Thinking",
      "Creativity",
      "Communication",
      "Leadership",
      "Problem Solving",
      "Technical Skills",
      "Empathy",
      "Organization",
      "Adaptability",
      "Research",
    ],
    validation: {
      maxSelections: 3,
    },
    required: true,
    group: "skills",
  },
  {
    id: "interests",
    question: "What topics interest you the most? (Select up to 3)",
    type: "multiSelect",
    options: [
      "Technology",
      "Science",
      "Arts",
      "Business",
      "Healthcare",
      "Education",
      "Environment",
      "Social Impact",
      "Innovation",
      "Research",
    ],
    validation: {
      maxSelections: 3,
    },
    required: true,
    group: "interests",
  },
  {
    id: "values",
    question: "What do you value most in a career? (Select up to 3)",
    type: "multiSelect",
    options: [
      "Work-Life Balance",
      "High Income",
      "Job Security",
      "Making a Difference",
      "Learning Opportunities",
      "Career Growth",
      "Innovation",
      "Social Impact",
      "Recognition",
      "Independence",
    ],
    validation: {
      maxSelections: 3,
    },
    required: true,
    group: "values",
  },
  {
    id: "passion",
    question: "What activities do you enjoy doing, even without payment?",
    type: "textarea",
    required: true,
    validation: {
      minLength: 50,
      maxLength: 500,
    },
    group: "aspirations",
  },
  {
    id: "impact",
    question: "What kind of impact would you like to make in your career?",
    type: "textarea",
    required: true,
    validation: {
      minLength: 50,
      maxLength: 500,
    },
    group: "aspirations",
  },
  {
    id: "fiveYearGoal",
    question: "Where do you see yourself in 5 years?",
    type: "textarea",
    required: true,
    validation: {
      minLength: 50,
      maxLength: 500,
    },
    group: "aspirations",
  },
];

export const CAREER_SUGGESTIONS: Record<string, CareerSuggestion> = {
  software_engineer: {
    title: "Software Engineer",
    confidence: 0.9,
    description:
      "Design, develop, and maintain software applications and systems.",
    skills: [
      "Programming",
      "Problem Solving",
      "System Design",
      "Debugging",
      "Version Control",
    ],
    education: [
      "Bachelor's in Computer Science",
      "Software Engineering Certifications",
    ],
    matchingFactors: {
      interests: ["Technology", "Innovation"],
      strengths: ["Analytical Thinking", "Problem Solving"],
      values: ["High Income", "Learning Opportunities"],
    },
    salary: {
      entry: 70000,
      mid: 120000,
      senior: 200000,
    },
    growthOutlook: "High",
    workEnvironment: ["Remote", "Office", "Hybrid"],
    sectors: ["Tech", "Finance", "Healthcare", "Entertainment"],
  },
  data_scientist: {
    title: "Data Scientist",
    confidence: 0.85,
    description: "Analyze complex data sets to help guide business decisions.",
    skills: [
      "Statistics",
      "Machine Learning",
      "Python/R",
      "Data Visualization",
      "SQL",
    ],
    education: ["Master's in Data Science", "Statistics or Related Field"],
    matchingFactors: {
      interests: ["Technology", "Science", "Research"],
      strengths: ["Analytical Thinking", "Research"],
      values: ["Innovation", "High Income"],
    },
    salary: {
      entry: 85000,
      mid: 130000,
      senior: 180000,
    },
    growthOutlook: "Very High",
    workEnvironment: ["Hybrid", "Office"],
    sectors: ["Tech", "Finance", "Healthcare", "Research"],
  },
  healthcare_administrator: {
    title: "Healthcare Administrator",
    confidence: 0.8,
    description:
      "Manage healthcare facilities and improve patient care systems.",
    skills: [
      "Leadership",
      "Healthcare Regulations",
      "Business Administration",
      "Communication",
      "Problem Solving",
    ],
    education: [
      "Master's in Healthcare Administration",
      "Business or Healthcare Management Degree",
    ],
    matchingFactors: {
      interests: ["Healthcare", "Business", "Social Impact"],
      strengths: ["Leadership", "Organization"],
      values: ["Making a Difference", "Job Security"],
    },
    salary: {
      entry: 65000,
      mid: 95000,
      senior: 150000,
    },
    growthOutlook: "High",
    workEnvironment: ["Office"],
    sectors: ["Healthcare", "Government", "Non-profit"],
  },
  environmental_scientist: {
    title: "Environmental Scientist",
    confidence: 0.75,
    description: "Study environmental problems and develop solutions.",
    skills: [
      "Research",
      "Data Analysis",
      "Environmental Regulations",
      "Field Work",
      "Report Writing",
    ],
    education: [
      "Bachelor's in Environmental Science",
      "Master's in Related Field",
    ],
    matchingFactors: {
      interests: ["Environment", "Science", "Social Impact"],
      strengths: ["Research", "Analytical Thinking"],
      values: ["Making a Difference", "Learning Opportunities"],
    },
    salary: {
      entry: 55000,
      mid: 85000,
      senior: 120000,
    },
    growthOutlook: "Moderate",
    workEnvironment: ["Field Work", "Laboratory", "Office"],
    sectors: ["Government", "Research", "Consulting", "Non-profit"],
  },
  ux_designer: {
    title: "UX Designer",
    confidence: 0.85,
    description: "Design user-friendly digital experiences and interfaces.",
    skills: [
      "User Research",
      "Wireframing",
      "Prototyping",
      "Visual Design",
      "Usability Testing",
    ],
    education: ["Bachelor's in Design", "UX/UI Certifications"],
    matchingFactors: {
      interests: ["Technology", "Arts", "Innovation"],
      strengths: ["Creativity", "Empathy"],
      values: ["Innovation", "Career Growth"],
    },
    salary: {
      entry: 65000,
      mid: 95000,
      senior: 140000,
    },
    growthOutlook: "High",
    workEnvironment: ["Remote", "Office", "Hybrid"],
    sectors: ["Tech", "Agency", "Consulting"],
  },
};
